// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIIxR7oftFuONsUupGG5QCHTSdNsZnoww',
    appId: '1:979415511220:web:68014337d53601c05d67e1',
    messagingSenderId: '979415511220',
    projectId: 'bapu-efdc8',
    authDomain: 'bapu-efdc8.firebaseapp.com',
    storageBucket: 'bapu-efdc8.firebasestorage.app',
    measurementId: 'G-K3448XSP5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqQXUbeQrG9D3EQZBHQncoqGPrAq1mONs',
    appId: '1:979415511220:android:6cb83774d4f326d85d67e1',
    messagingSenderId: '979415511220',
    projectId: 'bapu-efdc8',
    storageBucket: 'bapu-efdc8.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZvwmElzOUhRWKA6kwfJ8ZF4toVmXic-g',
    appId: '1:979415511220:ios:89c489f71a92ea095d67e1',
    messagingSenderId: '979415511220',
    projectId: 'bapu-efdc8',
    storageBucket: 'bapu-efdc8.firebasestorage.app',
    iosBundleId: 'com.wjddnwls7879.unistbab',
  );
}
